### ISSUE TITLE
Support of pnpm in sheweny create

### ISSUE THREAD

**Issue by Rapougnac** [Sheweny/cli#45]
I saw that there's currently only yarn & npm supported in the `sheweny create` command, that would be cool if [pnpm](https://pnpm.io) can be supported too. It's popularity's growing, and it's a nice alternative to npm, or yarn.

**Comment by Smaug6739** [comment]
Thanks for the issue, pnpm will be added in the next version

**Comment by Smaug6739** [comment]
Pnpm is now supported in version 2.1.1
